// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebShop.API.Products;

#nullable disable

namespace WebShop.API.Migrations.Products
{
    [DbContext(typeof(ProductsDbContext))]
    [Migration("20230923101431_Create_Database")]
    partial class Create_Database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("products")
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebShop.API.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products", "products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b9bb5000-77f0-402a-b02f-d1c7cb9c304e"),
                            Name = "Product #1",
                            Price = 100m
                        },
                        new
                        {
                            Id = new Guid("12c7f944-5c45-4c2e-805a-4c4bf4615c7a"),
                            Name = "Product #2",
                            Price = 200m
                        },
                        new
                        {
                            Id = new Guid("9406f5a6-0d6a-4708-8b64-aff6bb957ddb"),
                            Name = "Product #3",
                            Price = 300m
                        },
                        new
                        {
                            Id = new Guid("d32e75ee-32fc-4ea9-95b3-e41f3ccf7d2e"),
                            Name = "Product #4",
                            Price = 400m
                        },
                        new
                        {
                            Id = new Guid("55336abd-482d-4fca-800c-29d9ac471725"),
                            Name = "Product #5",
                            Price = 500m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
